spring:
  application:
    name: ticket-service
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  mvc:
    problemdetails:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: secret
    hikari:
      auto-commit: false
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
          lob:
            non_contextual_creation: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
          plan_cache_max_size: 4096
        connection:
          provider_disables_autocommit: true
    repositories:
      bootstrap-mode: deferred
  config:
    activate:
      on-profile: default
server:
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show_details: always
      group:
        liveness:
          include:
            - livenessState
            - diskSpace
            - ping
            - db
          show-details: always
        readiness:
          include:
            - readinessState
            - diskSpace
            - db
          show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    refresh:
      enabled: false
    circuitBreakers:
      enabled: true
